name: Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Create output directory
        run: mkdir -p ./dist

      - name: Test package
        uses: ./
        with:
          source-dir: ./test-extension
          output-dir: ./dist

      - name: Verify
        run: |
          test -f ./dist/*.shell-extension.zip
          unzip -l ./dist/*.shell-extension.zip

      - name: Extract and compare
        run: |
          mkdir -p ./extracted
          unzip -q ./dist/*.shell-extension.zip -d ./extracted
          diff -r ./test-extension ./extracted
