name: Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Test package
        uses: ./
        with:
          source-dir: ./test-extension
          output-dir: ./dist

      - name: Verify
        run: test -f ./dist/*.shell-extension.zip
